# Generated by Django 4.0.1 on 2022-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.TextField(default=None, verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
