# Generated by Django 4.0.1 on 2022-01-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Номер(а) товара(ов)')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('datetime', models.DateTimeField(verbose_name='Дата продажи')),
                ('total_price', models.IntegerField(verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('phone', models.IntegerField(max_length=10, verbose_name='Номер телефона')),
            ],
        ),
    ]
