# Generated by Django 4.0.1 on 2022-01-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customer_order_orderitem_shippinginformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(verbose_name='В наличии'),
        ),
    ]
