# Generated by Django 4.0.1 on 2022-01-17 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_receipt_total_price_remove_receipt_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orderitem'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer'),
        ),
    ]
