# Generated by Django 4.0.1 on 2022-01-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_receipt_total_price_alter_receipt_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='product_id',
            new_name='product',
        ),
    ]
