# Generated by Django 4.0.1 on 2022-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_receipt_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
