# Generated by Django 4.0.1 on 2022-01-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_customer_phone_customer_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
